codecov:
  require_ci_to_pass: yes
  ignore:
    - "Model"


coverage:
  precision: 2
  round: down
  range: "5...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
CODECOV_TOKEN=e5e9a1ac-93df-4a16-bd87-609381106e95
