ignore:
    - "utils"
    - "**/AddNewItem.java"
    - "**/UsedShoopingListTouchHelper.java"
    - "**/UnusedShoppingListTouchHelper.java"
    - "**/SplashActivity.java"
    - "**/SettingsActivity.java"
    - "**/ReminderActivity.java"
    - "**/NewItemTouchHelper.java"
    - "**/InventoryItemTouchHelper.java"
    - "**/InventoryActivity_old.java"
    - "**/HomeActivity.java"
    - "**/AlarmReceiver.java"
    - "**/AddNewShoppingList.java"
    
