ignore:
    - "**/AddNewItem.java"
    - "**/AddNewShoppingList.java"
    - "**/AlarmReceiver.java"
    - "**/HomeActivity_old.java"
    - "**/InventoryActivity.java"
    - "**/InventoryItemTouchHelper.java"
    - "**/ReminderActivity.java"
    - "**/Settings.java"
    - "**/SplashActivity.java"
    - "**/UsedShoppingListTouchHelper.java"
    - "**/UnusedShoppingListTouchHelper.java"
    - "**/UseShoppingListActivity.java"
    - "**/TabbedHomeActivity.java"
    - "**/TabbedInventoryActivity.java"
    - "**/NewItemTouchHelper.java"
    - "**/InventoryActivity_old.java"
        
