ignore:
    - "**/Fragments"
    - "**/AddNewItem.java"
    - "**/AddNewShoppingList.java"
    - "**/AlarmBrodcast.java"
    - "**/ItemCategoryActivity.java"
    - "**/PieChartActivity.java"
    - "**/ReminderActivity.java"
    - "**/TabbedHomeActivity.java"
    - "**/UsedShoppingListTouchHelper.java"
    - "**/UseShoppingListActivity.java"
    - "**/UnusedShoppingListTouchHelper.java"
    - "**/ShoppingListItemTouchHelper.java"
    - "**/ShoppingListReminder.java"
    - "**/SettingsActivity.java"
    - "**/ReminderMain.java"
    - "**/BarChartActivity.java"
    - "**/AlarmReceiver.java"
    - "**/AddShoppingListItemsActivity.java"
    - "**/AddNewInventoryItem.java"
    
