ignore:
    - "**/Activities"
    - "**/utils"
    - "**/PlaceholderFragmentInventory.java"
    - "**/PageViewModelInventory.java"
    - "**/PageViewModelHome.Java"
    - "**/PlaceholderFragmentHome.java"
    - "**/NotificationMessage.java"
    - "**/SplashActivity.java"
    
    
